apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  namespace: mini-marketplace
spec:
  rules:
  - host: users.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: users
            port:
              number: 80
